#!/bin/dash

# Checking .legit repo expo exist in current directory
if [ ! -d ".legit" ]
then
    echo "$0: error: no .legit directory containing legit repository exists" 1>&2
    exit 1
fi

# Checking invalid arguments supplied
#echo "$2"
if [ "$#" = "2" -a "$1" = "-m" ]  
then
    msg="$2"
else
    echo "usage: legit-commit [-a] -m commit-message" 1>&2
    exit 1
fi

#if echo "$msg" |
# If -a is passed in
#if egrep "\-a" > /dev/null

# Checking if message contains a new line

# Checking whether changes have been made to files in order to be committed
changes=`egrep "[0-9]+" < ".legit/index/.changes"`
if [ "$changes" -eq "0" ]
then
    echo "nothing to commit"
    exit 0
fi


# Create repo to store commited files if haven't already
if [ ! -d ".legit/repo" ]
then
    mkdir ".legit/repo"
fi

# Store sub-directories in .legit/repo/ for each commit, where n is the commit number
# Each directory is named .commit.n
n=0
fn=".commit"
while test -d ".legit/repo/$fn.$n"
do
    n=$((n + 1))
done

mkdir ".legit/repo/$fn.$n"

for file in ".legit/index"/*
do
    cp "$file" ".legit/repo/$fn.$n/"
done

# Write commit msg to file
echo "$n $msg" > ".legit/repo/$fn.$n/.msg"
