#!/bin/dash

# Checking .legit repo expo exist in current directory
if [ ! -d ".legit" ]
then
    echo "$0: error: no .legit directory containing legit repository exists" 1>&2
    exit 1
fi

# Checking commits have been made before using legit-log
if [ ! -d ".legit/repo/.commit.0" ]
then
    echo "$0: error: your repository does not have any commits yet"
    exit 1
fi

if [ "$#" != "1" ]
then
    echo fail
fi
