#!/bin/dash

# Checking that no cmd line args are supplied
if [ "$#" -ne 0 ]
then
    echo "usage: legit-init" 1>&2
    exit 1
fi

# Create a .legit directory, print error if already exists
if [ ! -d ".legit" ]
then
    mkdir ".legit"
    echo "Initialized empty legit repository in .legit"
else
    echo "$0: error: .legit already exists" 1>&2
    exit 1
fi
