#!/bin/dash

# Checking .legit repo expo exist in current directory
if [ ! -d ".legit" ]
then
    echo "$0: error: no .legit directory containing legit repository exists" 1>&2
    exit 1
fi

# Check correct usage
if [ "$#" -eq 0 ]
then
    echo "usage: $0 <filenames>" 1>&2
    exit 1
fi

for file in "$@"
do
    if echo "$file" | egrep "^\-" >/dev/null
    then
        echo "usage: $0 <filename>" 1>&2
        exit 1
    fi 
done

# Check valid file names and that they exist as a regular file
for fn in "$@"
do
    if echo "$fn" | egrep -v "^[a-zA-Z0-9][a-zA-Z0-9\.\-_]*" > /dev/null
    then
        echo "$0: error: invalid filename '$fn'" 1>&2
        exit 1
    fi
    
    if [ ! -e "$fn" -a ! -e ".legit/index/$fn" ]
    then
        echo "$0: error: can not open '$fn'" 1>&2
        exit 1
    fi
    # Storing only ordinary files in the index use -r or -f?    
    if [ ! -f "$fn" -a ! -e ".legit/index/$fn" ]  
    then
        echo "$0: error: '$fn' is not a regular file" 1>&2
        exit 1
    fi
done

# Create sub-directory to store files from legit-add if haven't already
if [ ! -d ".legit/index" ]
then
    mkdir ".legit/index"
fi

# legit-add all files supplied from command line args and record if changes
# have been made from the last time it was staged
for file in "$@" 
do   
    # If file deleted from working directory, also delete in index 
    if [ ! -f "$file" -a -f ".legit/index/$file" ]
    then
        rm ".legit/index/$file"
    else
        cp "$file" ".legit/index/"
    fi
done

