#!/bin/dash

# Checking .legit repo expo exist in current directory
if [ ! -d ".legit" ]
then
    echo "$0: error: no .legit directory containing legit repository exists" 1>&2
    exit 1
fi

# Checking invalid arguments supplied
if echo "$*" | egrep -v "^(-a )?\-m [^ ]+$" > /dev/null  
then
    echo "usage: legit-commit [-a] -m commit-message" 1>&2
    exit 1
fi

# If -a is passed in
#if egrep "\-a" > /dev/null
exit 0
##### CONSIDER CASE WHERE THERE IS NOTHING TO COMMIT #############
changes=`egrep "[0-9]+" < ".legit/index/.changes"`
if [ "$changes" -eq "0" ]
then
    echo "nothing to commit"
    exit 0
fi


# Create repo to store commited files if haven't already
if [ ! -d ".legit/repo" ]
then
    mkdir ".legit/repo"
fi

# Store sub-directories in .legit/repo/ for each commit, where n is the commit number
# Each directory is named .commit.n
n=0
fn=".commit"
while test -d "$fn.$n"
do
    n=$((n + 1))
done

mkdir ".legit/repo/$fn.$n"

for file in ".legit/index"/*
do
    cp "$file" ".legit/repo/$fn.$n/"
done

# Write to log file
msg=`echo "$*" | sed "s/^\-a //" | sed "s/\-m //"`
echo "$n $msg" >> ".legit/repo/.log"
