#!/bin/dash

# Checking .legit repo expo exist in current directory
if [ ! -d ".legit" ]
then
    echo "$0: error: no .legit directory containing legit repository exists" 1>&2
    exit 1
fi

# Checking valid arguments are supplied
if [ "$#" = "2" -a "$1" = "-m" ]  
then
    msg="$2"
elif [ "$#" = "3" -a "$1" = "-a" -a "$2" = "-m" ]
then
    msg="$3"
    
    # Update all files currently in index with the version in curr directory
    for file in ".legit/index"/*
    do
        file=`basename $file`
        legit-add "$file" #-> use this for autotest because curr dir is appended to $PATH
        #./legit-add "$file" 

    done
else
    echo "usage: legit-commit [-a] -m commit-message" 1>&2
    exit 1
fi

#if echo "$msg" |
# If -a is passed in
#if egrep "\-a" > /dev/null

# Checking if message contains a new line

# Checking whether changes have been made to files in order to be committed
# by comparing all files between last commit and staging area
diff=0
if [ -d ".legit/repo/.commit.0" ]
then
    # Get last commit number
    n=0
    while test -d ".legit/repo/.commit.$n"
    do
        n=$((n + 1))
    done
    n=$((n - 1))

    # Compare files from .commit.n with index
    for file in ".legit/repo/.commit.$n"/*
    do
        fn=`echo "$file" | sed "s/.legit\/repo\/.commit.$n\///g"`
        if  ! diff ".legit/repo/.commit.$n/$fn" ".legit/index/$fn" >/dev/null 2>&1
        then
            diff=1
            break
        fi
    done

    # Compare files from index with .commit.n
    for file in ".legit/index"/*
    do
        fn=`echo "$file" | sed "s/.legit\/index\///g"`
        if ! diff ".legit/index/$fn" ".legit/repo/.commit.$n/$fn" >/dev/null 2>&1
        then
            diff=1
            break
        fi
    done
    
    # If both index and .commit.n are empty
    if [ `ls ".legit/index/" | wc -l` = 0 -a `ls ".legit/repo/.commit.$n/" | wc -l` = 0 ]
    then
        diff=0
    fi

else
    # This is the first commit
    n="-1"
fi

# If this is not the first commit and there are no differences between files
if [ "$n" != "-1" -a "$diff" = "0" ]
then
    echo "nothing to commit"
    exit 0   
fi

# Create repo to store commited files if haven't already
if [ ! -d ".legit/repo" ]
then
    mkdir ".legit/repo"
fi

# Store sub-directories in .legit/repo/ for each commit, where n is the commit number
# Each directory is named .commit.n
n=0
fn=".commit"
while test -d ".legit/repo/$fn.$n"
do
    n=$((n + 1))
done

mkdir ".legit/repo/$fn.$n"

# Commit all the files in index to .commit.n directory
for file in ".legit/index"/*
do
    # If index/ is empty, file will expand to the literal string ".legit/index/*" 
    # rather than look inside the directory for any files
    if [ "$file" != ".legit/index/*" ]
    then
        cp "$file" ".legit/repo/$fn.$n/"
    fi    
done

echo "Committed as commit $n"

# Write commit msg to file
echo "$n $msg" > ".legit/repo/$fn.$n/.msg"
