#!/bin/dash

# Checking .legit repo expo exist in current directory
if [ ! -d ".legit" ]
then
    echo "$0: error: no .legit directory containing legit repository exists" 1>&2
    exit 1
fi

# Checking commits have been made before using legit-log
if [ ! -d ".legit/repo/.commit.0" ]
then
    echo "$0: error: your repository does not have any commits yet"
    exit 1
fi

# Checking correct usage
if [ "$#" != "0" ]
then
    echo "usage: $0" 1>&2
    exit 1
fi

# Output each commit # and message in most recent order
n=0
while [ -d ".legit/repo/.commit.$n" ]
do
    n=$((n + 1))
done
n=$((n - 1))

while [ "$n" -ge "0" ]
do
    cat ".legit/repo/.commit.$n/.msg"
    n=$((n - 1))
done

